<a href="https://colab.research.google.com/github/Venkateshyakkala007/Numpy/blob/main/1_june23_np_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
DAV -> Data Analysis and Visualization

DAV-1 : Numpy, Pandas, Matplotlib and Seaborn
DAV-2 : Probability and Stats
DAV-3 : Hypothesis testing

'''

'\nDAV -> Data Analysis and Visualization\n\nDAV-1 : Numpy, Pandas, Matplotlib and Seaborn\nDAV-2 : Probability and Stats\nDAV-3 : Hypothesis testing\n\n'

In [ ]:
a = [1, 2, "AJ", 7.6]
type(a)

list

<img src="https://drive.google.com/uc?id=1lgwART77tbifHMJjw-d4NV7aEpr0LVat">

In [ ]:
#speed comparison

In [ ]:
l = range(10000000)

In [ ]:
%timeit [i**2 for i in l]

3.88 s ± 504 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
type(l)

range

In [ ]:
import numpy as np

In [ ]:
b = np.array(l)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operations

In [ ]:
%timeit b ** 2

31.6 ms ± 897 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
type(b)

numpy.ndarray

In [ ]:
type(l)

range

In [ ]:
b.ndim

1

In [ ]:
b.shape

(10000000,)

In [ ]:
len(b)

10000000

In [ ]:
c = np.arange(1,5)
print(c)

[1 2 3 4]


In [ ]:
type(c)

numpy.ndarray

In [ ]:
c = np.arange(1,5,0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
a = [1,3, "AJ"]
print(a)

[1, 3, 'AJ']


In [ ]:
type(a)

list

In [ ]:
b = np.array(a)
print(b)

['1' '3' 'AJ']


In [ ]:
a = [5,7,2,6]
type(a)

list

In [ ]:
b = np.array(a)
print(b)

[5 7 2 6]


In [ ]:
c = np.array(a, dtype = "float")
print(c)

[5. 7. 2. 6.]


In [ ]:
#Quiz

d = np.array([4,8,4.3, 9])
print(d)

[4.  8.  4.3 9. ]


In [ ]:
#Quiz

a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
#Quiz

np.array(["AJ", "Yo", "Hi"], dtype = "float")

ValueError: ignored

In [ ]:
a = np.array([10,20,30,40,50])
type(a)


numpy.ndarray

In [ ]:
print(a)

[10 20 30 40 50]


In [ ]:
a = a.astype("float")
print(a)

[10. 20. 30. 40. 50.]


In [ ]:
a.dtype

dtype('float64')

In [ ]:
#Quiz:

b = np.arange(4,9,0.5)
print(b)

[4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


<img src="https://drive.google.com/uc?id=1GSV_E1CaCc_Ur7pWJ-Kqv0VKvBRwByR1">

In [ ]:
b = np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
b[3]

3

In [ ]:
b[-1]

11

In [ ]:
#Resume at 10:03 sharp

In [ ]:
b = np.arange(1,15,2)
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[2:4]

array([5, 7])

In [ ]:
b[-2]

11

In [ ]:
b[3:]

array([ 7,  9, 11, 13])

In [ ]:
b[:2]

array([1, 3])

In [ ]:
#multi-indexing

In [ ]:
b[2]

5

In [ ]:
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[5]

11

In [ ]:
b[ [2,5] ]

array([ 5, 11])

In [ ]:
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[ [ 5,2,4]  ]

array([11,  5,  9])

In [ ]:
#Quiz

import numpy as np

arr = np.arange(5)
arr[2:4] = 0

print(arr)

[0 1 0 0 4]


In [ ]:
#Fancy indexing - Masking

In [ ]:
a = np.arange(1,12)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b = a < 6
print(b)

[ True  True  True  True  True False False False False False False]


In [ ]:
print(a[a<6])

[1 2 3 4 5]


In [ ]:
#filter all the even elements using fancy indexing

b = a[a%2 == 0]
print(b)

[ 2  4  6  8 10]


In [ ]:
#filter all the odd elements using fancy indexing

b = a[a%2 != 0]
print(b)

[ 1  3  5  7  9 11]


In [ ]:
#Quiz:

import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
#doubt
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a[4:])

[4 5]


In [ ]:
#Quiz
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]

In [ ]:
print(a)

[1, 2, 6, 7, 8]


In [ ]:
#Quiz

a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
#NPS: Net Promoter Score

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")
print(score[:5])

[ 7 10  5  9  9]


<img src="https://drive.google.com/uc?id=1-u8e-v_90JdikorKsKzBM-JJqoRtzsN8">

<img src="https://drive.google.com/uc?id=1KPIYlaN68vlL99iApaF5QbeBoyT24-Eu">

In [ ]:
score[:10]

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [ ]:
score.shape

(1167,)

In [ ]:
promoters_rating = score[score > 8]
print(promoters_rating)

[10  9  9  9  9  9 10  9  9 10  9  9  9  9  9  9  9 10 10  9 10  9 10  9
  9 10 10  9 10  9 10 10 10  9  9 10 10 10  9 10  9 10  9  9  9 10  9  9
  9  9  9  9 10  9  9  9 10  9 10  9  9  9  9  9 10 10  9 10  9  9 10  9
  9 10  9  9  9  9  9  9  9  9  9  9  9 10  9  9  9  9  9  9  9  9 10  9
  9  9  9  9 10 10  9 10 10 10 10  9 10  9  9  9  9  9  9  9 10  9 10  9
 10  9 10 10 10  9  9 10 10  9  9  9  9 10  9  9  9  9 10 10  9  9  9 10
  9  9  9  9  9 10  9  9  9 10  9 10 10  9  9  9  9 10  9 10  9  9  9  9
 10  9 10  9  9  9  9  9  9  9  9  9  9  9 10 10  9  9  9 10  9 10 10 10
 10 10  9  9  9  9 10 10 10  9  9 10  9 10 10 10 10  9 10 10  9 10  9  9
  9  9 10  9 10  9 10  9  9  9  9 10  9  9  9  9  9 10  9 10 10  9 10 10
 10  9  9  9  9  9  9 10  9  9 10  9 10 10  9  9  9 10 10 10 10  9  9  9
 10 10  9 10  9  9  9 10  9  9  9  9  9  9  9  9  9  9 10  9  9  9 10  9
 10  9 10  9 10  9  9 10 10  9  9  9 10  9  9 10  9  9  9  9  9  9 10 10
  9 10  9  9  9  9 10  9  9  9  9 10  9 10  9 10  9

In [ ]:
promoters_count = len(promoters_rating)
print(promoters_count)

609


In [ ]:
detractors = score[score < 7]
print(detractors)

[5 4 4 5 1 5 5 1 4 5 4 4 4 5 1 4 1 4 1 5 5 1 1 4 1 5 4 1 1 4 1 5 1 4 4 1 1
 1 1 1 1 1 4 1 1 5 5 5 4 4 1 4 1 4 1 5 1 1 5 4 4 4 4 1 4 5 4 4 1 1 5 5 1 5
 1 5 5 4 5 4 1 1 1 1 4 1 4 4 5 4 1 1 1 1 5 4 5 5 4 1 5 1 4 4 1 1 1 4 4 5 5
 4 5 5 5 1 4 1 5 5 1 5 1 1 5 5 4 4 1 4 4 4 1 1 4 4 4 5 5 1 1 4 1 4 1 4 1 4
 1 4 1 5 4 4 5 1 4 5 5 5 1 5 4 1 1 5 5 5 4 5 4 4 1 4 4 4 4 5 1 5 5 1 4 4 5
 1 1 4 5 5 5 1 4 5 5 4 1 5 5 5 1 1 5 5 1 1 1 4 5 5 4 4 4 5 1 4 1 4 5 4 5 5
 1 5 1 5 5 1 4 5 5 4 1 5 1 4 1 4 1 1 1 1 1 1 4 1 5 4 5 1 5 1 5 4 4 4 4 5 5
 1 4 1 5 5 1 4 1 1 4 4 4 4 1 4 1 1 4 1 5 4 1 1 5 4 5 4 4 4 1 5 5 1 4 5 4 4
 4 1 4 1 4 4 4 5 1 1 1 4 5 5 1 5 4 5 5 4 1 1 5 5 5 1 4 5 4 5 5 5 1 4 1 5]


In [ ]:
detractors_count = len(detractors)
print(detractors_count)

332


In [ ]:
609 + 332

941

In [ ]:
#HW --> Try to validate the number of passives

In [ ]:
total = len(score)
print(total)

1167


In [ ]:
perc_promoters = promoters_count*100/total
print(perc_promoters)

52.18508997429306


In [ ]:
perc_detractors = detractors_count*100/total
print(perc_detractors)

28.449014567266495


In [ ]:
nps = perc_promoters - perc_detractors
print(nps)

23.73607540702656


In [ ]:
nps = np.round(nps, 2)
print(nps)

23.74


In [ ]:
score.min()

1

In [ ]:
score.max()

10