<a href="https://colab.research.google.com/github/Venkateshyakkala007/Numpy/blob/main/june23_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("fit.txt", dtype = "str")

In [ ]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [ ]:
data.ndim

2

In [ ]:
data.shape

(96, 6)

In [ ]:
print(data[0])

['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']


In [ ]:
print(data[2])

['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']


In [ ]:
print(data[:5])

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']]


In [ ]:
data_t = data.T #Transpose
print(data_t)

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [ ]:
data_t.shape

(6, 96)

In [ ]:
data.shape

(96, 6)

In [ ]:
data_t.shape

(6, 96)

In [ ]:
rows = data_t.shape[0]
cols = data_t.shape[1]

In [ ]:
rows

6

In [ ]:
cols

96

In [ ]:
print(data_t)

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [ ]:
dates = data_t[0]
print(dates)

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
 '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
 '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
 '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
 '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
 '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
 '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
 '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
 '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
 '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2017'
 '20-12-20

In [ ]:
dates.ndim

1

In [ ]:
dates.shape

(96,)

In [ ]:
print(data_t)

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [ ]:
step_count = data_t[1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [ ]:
step_count = step_count.astype("int")
print(step_count)

[5464 6041   25 5461 6915 4545 4340 1230   61 1258 3148 4687 4732 3519
 1580 2822  181 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 6676 3608
  774 1421 4064 2725 5934 1867 3721 2374 2909 1648  799 7102 3941 7422
  437 1231 1696 4921  221 6500 3575 4061  651  753  518 5537 4108 5376
 3066  177   36  299 1447 2599  702  133  153  500 2127 2203]


In [ ]:
# step_count = np.array(step_count, dtype = "int")

In [ ]:
np.mean(step_count) #average step count in the given data

2935.9375

In [ ]:
#version2

In [ ]:
print(data[:5])

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']]


In [ ]:
step_count = data[: , 1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [ ]:
step_count = step_count.astype("int")
print(step_count)

[5464 6041   25 5461 6915 4545 4340 1230   61 1258 3148 4687 4732 3519
 1580 2822  181 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 6676 3608
  774 1421 4064 2725 5934 1867 3721 2374 2909 1648  799 7102 3941 7422
  437 1231 1696 4921  221 6500 3575 4061  651  753  518 5537 4108 5376
 3066  177   36  299 1447 2599  702  133  153  500 2127 2203]


In [ ]:
mood = data[:, 2]
print(mood)

['Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad'
 'Sad' 'Happy' 'Sad' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Neutral'
 'Neutral' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Sad'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Sad' 'Neutral'
 'Neutral' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Neutral'
 'Sad' 'Neutral' 'Sad' 'Neutral' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Happy'
 'Neutral' 'Happy' 'Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Sad'
 'Sad' 'Happy' 'Neutral' 'Neutral' 'Happy']


In [ ]:
#store all the step counts on the days where mood was Happy

In [ ]:
step_count_happy = step_count[ mood == "Happy" ] #step count where the mood was Happy
print(step_count_happy)

[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
len(step_count_happy)

40

In [ ]:
#Find the average number of step counts that the person takes when their mood is Sad?

In [ ]:
step_count_sad = step_count[ mood == "Sad" ]
len(step_count_sad)

29

In [ ]:
sad_avg_step_count = np.mean(step_count_sad)
print(sad_avg_step_count)

2103.0689655172414


In [ ]:
#Find the average number of steps when the mood is Happy?

In [ ]:
mood == "Happy"

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [ ]:
step_count_happy = step_count[ mood == "Happy" ]
len(step_count_happy)

40

In [ ]:
happy_avg_step_count = np.mean(step_count_happy)
print(happy_avg_step_count)

3392.725


In [ ]:
#Question: Find the step counts of the days when mood is either Happy or Neutral?

In [ ]:
step_count_happy_or_neutral = step_count[(mood == "Happy") | (mood == "Neutral")] #or --> |, and --> &
print(step_count_happy_or_neutral)

[5464 6915 4732 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 3608  774
 1421 4064 2725 5934 1867 2374 2909 7102 3941 7422  437 1231 4921 6500
 3575 5537 4108 5376 3066 1447 2599  153  500 2127 2203]


In [ ]:
len(step_count_happy_or_neutral)

67

In [ ]:
happy_or_neutral_avg = np.mean(step_count_happy_or_neutral)
print(happy_or_neutral_avg)

3296.4328358208954


In [ ]:
happy_or_neutral_avg = np.round(happy_or_neutral_avg, 2)
print(happy_or_neutral_avg)

3296.43


In [ ]:
#What was the mood of the person on "06-10-2017"?

print(dates)

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
 '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
 '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
 '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
 '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
 '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
 '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
 '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
 '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
 '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2017'
 '20-12-20

In [ ]:
print(mood)

['Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad' 'Sad'
 'Sad' 'Happy' 'Sad' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Neutral'
 'Neutral' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Happy' 'Happy'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Neutral' 'Sad'
 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Happy' 'Sad' 'Neutral'
 'Neutral' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Happy' 'Neutral' 'Neutral'
 'Sad' 'Neutral' 'Sad' 'Neutral' 'Neutral' 'Sad' 'Sad' 'Sad' 'Sad' 'Happy'
 'Neutral' 'Happy' 'Neutral' 'Sad' 'Sad' 'Sad' 'Neutral' 'Neutral' 'Sad'
 'Sad' 'Happy' 'Neutral' 'Neutral' 'Happy']


In [ ]:
ans = mood[ dates == "06-10-2017"]
print(ans)

['Neutral']


In [ ]:
type(ans)

numpy.ndarray

In [ ]:
new_mood = ans[0]
print(new_mood)

Neutral


In [ ]:
type(new_mood)

numpy.str_

In [ ]:
#General concepts

In [ ]:
b = np.arange(16)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
b.ndim

1

In [ ]:
b.shape

(16,)

In [ ]:
#reshape

c = b.reshape(8, 2)

In [ ]:
print(c)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
c.shape

(8, 2)

In [ ]:
d = b.reshape(8, 3)

ValueError: ignored

In [ ]:
d = b.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
d = b.reshape(8, -1)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
d = b.reshape(3, -1)
print(d)

ValueError: ignored

In [ ]:
d = b.reshape(4, -5)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
d = b.reshape(-1, 8)
print(d)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
d.shape

(2, 8)

In [ ]:
d = b.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
print(d[1])

[4 5 6 7]


In [ ]:
#Quiz

a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1

In [ ]:
print(a)

[-1  1 -1  3 -1  5]


In [ ]:
d = b.reshape(4,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#indexing in 2D numpy array

In [ ]:
print(d[1])

[4 5 6 7]


In [ ]:
print(d[1][3])

7


In [ ]:
print(d[1 , 3])

7


In [ ]:
print(d[2,3])

11


In [ ]:
print(d[2,4])

IndexError: ignored

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#creating 1D np array


a = np.array([5,7,2])
print(a)

[5 7 2]


In [ ]:
#creating 2D np array


a = np.array([[4,8,1], [5,7,2]])
print(a)

[[4 8 1]
 [5 7 2]]


In [ ]:
a.ndim

2

In [ ]:
a = np.arange(1, 10 , 2)
print(a)

[1 3 5 7 9]


In [ ]:
m1 = np.arange(1, 10).reshape(3,3)
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#multi-indexing in 1D

a = np.arange(5,10)
print(a)

[5 6 7 8 9]


In [ ]:
print(a[[4,1]])

[9 6]


In [ ]:
#multi-indexing in 2D

m1 = np.arange(1, 10).reshape(3,3)
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(m1[ [0,1,2] , [0,1,2] ])

[1 5 9]


In [ ]:
print(m1[ [0,1,2] , [2,0,1] ])

[3 4 8]


In [ ]:
#slicing in 2D

a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
print(a[:, 0:2])

[[0 1]
 [4 5]
 [8 9]]


In [ ]:
print(a[:, 1:3])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [ ]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[0:2 , 1:3] )

[[1 2]
 [5 6]]


In [ ]:
print(a[1, 1:3])

[5 6]


In [ ]:
#Fancy indexing - masking in 2D

In [ ]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a<6)

[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [ ]:
print(a[a<6])

[0 1 2 3 4 5]


In [ ]:
a = np.arange(3)
print(a)

[0 1 2]


In [ ]:
a.sum()

3

In [ ]:
a.mean()

1.0

In [ ]:
a.min()

0

In [ ]:
#aggregation in 2D

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
np.sum(a, axis = 0) #column-wise sum

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis = 1) #row-wise sum

array([ 6, 22, 38])

In [ ]:
#logical operations

In [ ]:
a = np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [ ]:
a < 3

array([ True,  True,  True, False, False, False, False])

In [ ]:
np.any(a<3)

True

In [ ]:
np.any(a<5)

True

In [ ]:
np.any(a>10)

False

In [ ]:
np.all(a<3)

False

In [ ]:
np.all(a<10)

True

In [ ]:
#Quiz

a = np.array([0,2,3])
b = np.array([1,3,5])

a >= b #element wise comparison

array([False, False, False])

In [ ]:
np.any(a>=b)

False

In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr[arr > 0] = 1
arr[arr < 0] = -1
print(arr)

[-1  1  1  1 -1  0 -1 -1  1  0]


In [ ]:
#where

In [ ]:
a = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])

In [ ]:
print(a)

[ -3   4  27  34  -2   0 -45 -11   4   0]


In [ ]:
b = np.where(a >= 0, "pos", "neg")

In [ ]:
print(b)

['neg' 'pos' 'pos' 'pos' 'neg' 'pos' 'neg' 'neg' 'pos' 'pos']


In [ ]:
print(a)

[ -3   4  27  34  -2   0 -45 -11   4   0]


In [ ]:
print(np.where(a)) #gives index of all the non-zero elements - special case

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
#doubts

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[::2, 0::3]

array([[ 0,  3],
       [ 8, 11]])